/*

PARA PROBAR EL PROCEDURE

*/

UPDATE WEST_WORLD.Empresa
SET diaRendicion = DAY(GETDATE())
WHERE idEmpresa = 1

INSERT INTO WEST_WORLD.Factura 
SELECT TOP 20 numeroFactura + 100000, cliente, empresa, getdate(), getdate(), total, NULL, pago + 100000
FROM WEST_WORLD.Factura


INSERT INTO WEST_WORLD.Pago
SELECT TOP 20 numeroPago + 100000, FechaCobro, cliente, sucursal, importe, formaPago
FROM WEST_WORLD.Pago

UPDATE WEST_WORLD.Pago
SET FechaCobro = CONVERT(DATETIME, '2017-11-25')
WHERE numeroPago BETWEEN 100001 AND 100018





CREATE OR ALTER PROCEDURE RendicionDeFacturas @EMPRESA INT, @PORCENTAJE INT
AS
BEGIN
DECLARE @FECHA_INICIO DATETIME, @FECHA_ACTUAL DATETIME, @PORCENTAJE_CALCULO FLOAT
SET @FECHA_ACTUAL = GETDATE()
SET @FECHA_INICIO = DATEADD(month, -1, @FECHA_ACTUAL)
SET @PORCENTAJE_CALCULO = @PORCENTAJE / 100

IF DAY(@FECHA_ACTUAL) = (SELECT E.diaRendicion FROM WEST_WORLD.Empresa E WHERE E.idEmpresa = @EMPRESA)

INSERT INTO WEST_WORLD.Rendicion
SELECT @FECHA_ACTUAL, COUNT(DISTINCT F.numeroFactura) as CantidadDeFacturas, SUM(F.total) - SUM(F.total) * @PORCENTAJE_CALCULO  as ImporteRendido, empresa , @PORCENTAJE as Porcentaje, SUM(F.total) ImporteTotal
FROM WEST_WORLD.Factura F
LEFT JOIN WEST_WORLD.Pago P ON P.numeroPago = F.pago
WHERE empresa = @EMPRESA AND P.FechaCobro BETWEEN @FECHA_INICIO AND @FECHA_ACTUAL
GROUP BY empresa

UPDATE WEST_WORLD.Factura
SET rendicion = (SELECT R.numeroRendicion FROM WEST_WORLD.Rendicion R WHERE R.empresa = @EMPRESA AND R.FechaRendicion = @FECHA_ACTUAL)
WHERE numeroFactura in (SELECT F.numeroFactura FROM WEST_WORLD.Factura F
LEFT JOIN WEST_WORLD.Pago P ON P.numeroPago = F.pago
WHERE empresa = @EMPRESA AND P.FechaCobro BETWEEN @FECHA_INICIO AND @FECHA_ACTUAL)



END

EXECUTE RendicionDeFacturas 1, 15


/* PARA VER SI FUNCA */



DECLARE @FECHA_ACTUAL DATETIME
SET @FECHA_ACTUAL = GETDATE()


SELECT *
FROM WEST_WORLD.Factura
WHERE fechaAlta BETWEEN DATEADD(MONTH, -1, @FECHA_ACTUAL) AND @FECHA_ACTUAL

DECLARE @FECHA_ACTUAL DATETIME
SET @FECHA_ACTUAL = GETDATE()

SELECT * 
FROM WEST_WORLD.Rendicion
WHERE DAY(FechaRendicion) = DAY(@FECHA_ACTUAL) AND MONTH(FechaRendicion) = MONTH(@FECHA_ACTUAL)
