CREATE PROCEDURE WEST_WORLD.RendicionCreate
@FECHA_RENDICION datetime,
@IDEMPRESA bigint,
@CANT_FACTURAS smallint,
@IMPORTE_NETO numeric(15,2),
@IMPORTE_TOTAL numeric(15,2),
@PORCENTAJE_COMISION nvarchar(50)

AS
	
	INSERT INTO WEST_WORLD.Rendicion(cantidadFacturas, empresa, FechaRendicion, importeNeto, importeTotal, porcentajeComision)
		VALUES(@CANT_FACTURAS, @IDEMPRESA, @FECHA_RENDICION, @IMPORTE_NETO, @IMPORTE_TOTAL, @PORCENTAJE_COMISION)

RETURN SCOPE_IDENTITY()